<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-02T00:58:01 IST" name="Default Suite" finished-at="2024-11-02T00:58:01 IST" duration-ms="89">
    <groups>
      <group name="Regression">
        <method signature="LoginTest.verifyUserCannotLoginWithInvalidCred()[pri:0, instance:com.automation.testng.LoginTest@f8c1ddd]" name="verifyUserCannotLoginWithInvalidCred" class="com.automation.testng.LoginTest"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2024-11-02T00:58:01 IST" name="SeleniumProject" finished-at="2024-11-02T00:58:01 IST" duration-ms="89">
      <class name="com.automation.testng.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.automation.testng.LoginTest@f8c1ddd]" started-at="2024-11-02T00:58:01 IST" name="setUp" finished-at="2024-11-02T00:58:01 IST" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUserCannotLoginWithInvalidCred()[pri:0, instance:com.automation.testng.LoginTest@f8c1ddd]" started-at="2024-11-02T00:58:01 IST" name="verifyUserCannotLoginWithInvalidCred" finished-at="2024-11-02T00:58:01 IST" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [hg] but found [gh]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [hg] but found [gh]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.automation.testng.LoginTest.verifyUserCannotLoginWithInvalidCred(LoginTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCannotLoginWithInvalidCred -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:com.automation.testng.LoginTest@f8c1ddd]" started-at="2024-11-02T00:58:01 IST" name="cleanUp" finished-at="2024-11-02T00:58:01 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.automation.testng.LoginTest -->
    </test> <!-- SeleniumProject -->
  </suite> <!-- Default Suite -->
</testng-results>
